"""Built-in reference sequences bundled with seqseeker."""

BUILTIN_SEQUENCES = {
    "egfp": {
        "description": "Enhanced GFP (canonical, non-codon-optimised)",
        "length": 720,
        "sequence": (
            "ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAAC"
            "GGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCT"
            "GCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCCTGACCTACGGCGTGCAGTGCTTCAGC"
            "CGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCAC"
            "CATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACC"
            "GCATCGAGCTGAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGGAGTACAACTACAAC"
            "AGCCACAACGTCTATATCATGGCCGACAAGCAGAAGAACGGCATCAAGGTGAACTTCAAGATCCGCCACAACAT"
            "CGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCCGTGCTGCTGC"
            "CCGACAACCACTACCTGAGCACCCAGTCCGCCCTGAGCAAAGACCCCAACGAGAAGCGCGATCACATGGTCCTG"
            "CTGGAGTTCGTGACCGCCGCCGGGATCACTCTCGGCATGGACGAGCTGTACAAGTAA"
        ),
    },
    "venus": {
        "description": "Venus YFP (T203Y/S65G/V68L/S72A mutations on eGFP)",
        "length": 720,
        "sequence": (
            "ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAAC"
            "GGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCT"
            "GCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCCTGACCTACGGCGTGCAGTGCTTCAGC"
            "CGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCAC"
            "CATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACC"
            "GCATCGAGCTGAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGGAGTACAACTACAAC"
            "AGCCACAACGTCTATATCATGGCCGACAAGCAGAAGAACGGCATCAAGGTGAACTTCAAGATCCGCCACAACAT"
            "CGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCCGTGCTGCTGC"
            "CCGACAACCACTACCTGAGCACCCAGTCCGCCCTGAGCAAAGACCCCAACGAGAAGCGCGATCACATGGTCCTG"
            "CTGGAGTTCGTGACCGCCGCCGGGATCACTCTCGGCATGGACGAGCTGTACAAGTAT"
        ),
    },
    "mcherry": {
        "description": "mCherry red fluorescent protein",
        "length": 711,
        "sequence": (
            "ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGTTCATGCGCTTCAAGGTGCACATGGAGG"
            "GCAGCATGAACGGCCACGAGTTCGAGATCGAGGGCGAGGGCGAGGGCCGCCCCTACGAGGGCACCCAGACCGCC"
            "AAGCTGAAGGTGACCAAGGGTGGCCCCCTGCCCTTCGCCTGGGACATCCTGTCCCCTCAGTTCATGTACGGCTCC"
            "AAGGCCTACGTGAAGCACCCCGCCGACATCCCCGACTACTTGAAGCTGTCCTTCCCCGAGGGCTTCAAGTGGGAG"
            "CGCGTGATGAACTTCGAGGACGGCGGCGTGGTGACCGTGACCCAGGACTCCTCCCTGCAGGACGGCGAGTTCATC"
            "TACAAGGTGAAGCTGCGCGGCACCAACTTCCCCTCCGACGGCCCCGTAATGCAGAAGAAGACCATGGGCTGGGAG"
            "GCCTCCTCCGAGCGGATGTACCCCGAGGACGGCGCCCTGAAGGGCGAGATCAAGCAGAGGCTGAAGCTGAAGGAC"
            "GGCGGCCACTACGACGCTGAGGTCAAGACCACCTACAAGGCCAAGAAGCCCGTGCAGCTGCCCGGCGCCTACAAC"
            "GTCAACATCAAGTTGGACATCACCTCCCACAACGAGGACTACACCATCGTGGAACAGTACGAACGCGCCGAGGGC"
            "CGCCACTCCACCGGCGGCATGGACGAGCTGTACAAGTAA"
        ),
    },
    "tdtomato": {
        "description": "tdTomato (tandem dimer Tomato)",
        "length": 1386,
        "sequence": (
            "ATGGTGAGCAAGGGCGAGGAGGTCATCAAAGAGTTCATGCGCTTCAAGGTGCGCATGGAAGGCTCCATGAACGG"
            "CCACGAGTTTGAGATCGAAGGCGAAGGCGAAGGCCGCCCCTACGAAGGCACCCAGACCGCCAAGCTGAAGGTGAC"
            "CAAGGGCGGCCCCCTGCCCTTCGCCTGGGACATCCTGTCGCCTCAGTTCATGTACGGCTCCAGGGCCTTCGTGAAG"
            "CACCCCGCCGACATCCCCGACTACAAGAAGCTGTCCTTCCCCGAAGGCTTCAAGTGGGAGCGCGTGATGAACTTCG"
            "AGGATGGCGGCGTGGTGACCGTGACACAGGACTCCTCCTTACAAGATGGCGAATTCATCTACAAGGTTAAGCTTCG"
            "CGGCACCAACTTCCCATCCGATGGCCCTGTAATGCAAAAGAAAACAATGGGCTGGGAAGCCTCCACCGAGCGCATG"
            "TACCCTGAGGATGGCGCCTTGAAGGGCGAAATAAGCCAGAGGTTGAAACTGAAGGACGGCGGTCACTACGATGCCG"
            "AGGTCAAGACCACGTACAAGGCCAAGAAGCCCGTGCAGCTGCCCGGCGCCTACAACGTCAATATCAAGTTGGACATC"
            "ACCTCCCATAACGAGGATTATACCATCGTTGAGCAGTACGAGCGGGCCGAAGGCCGGCACTCCACCGGCGGCATGG"
            "ACGAGCTGTACAAGGCGGCCATGGTGAGCAAGGGCGAGGAGGTCATCAAAGAGTTCATGCGCTTCAAGGTGCGCAT"
            "GGAAGGCTCCATGAACGGCCACGAGTTTGAGATCGAAGGCGAAGGCGAAGGCCGCCCCTACGAAGGCACCCAGACC"
            "GCCAAGCTGAAGGTGACCAAGGGCGGCCCCCTGCCCTTCGCCTGGGACATCCTGTCGCCTCAGTTCATGTACGGCT"
            "CCAGGGCCTTCGTGAAGCACCCCGCCGACATCCCCGACTACAAGAAGCTGTCCTTCCCCGAAGGCTTCAAGTGGGAG"
            "CGCGTGATGAACTTCGAGGATGGCGGCGTGGTGACCGTGACACAGGACTCCTCCTTACAAGATGGCGAATTCATCTA"
            "CAAGGTTAAGCTTCGCGGCACCAACTTCCCATCCGATGGCCCTGTAATGCAAAAGAAAACAATGGGCTGGGAAGCCT"
            "CCACCGAGCGCATGTACCCTGAGGATGGCGCCTTGAAGGGCGAAATAAGCCAGAGGTTGAAACTGAAGGACGGCGGT"
            "CACTACGATGCCGAGGTCAAGACCACGTACAAGGCCAAGAAGCCCGTGCAGCTGCCCGGCGCCTACAACGTCAATAT"
            "CAAGTTGGACATCACCTCCCATAACGAGGATTATACCATCGTTGAGCAGTACGAGCGGGCCGAAGGCCGGCACTCCA"
            "CCGGCGGCATGGACGAGCTGTACAAGTAA"
        ),
    },
}


def list_sequences() -> None:
    """Print a table of built-in sequences to stdout."""
    print(f"{'Name':<14} {'Length':>8}  Description")
    print("-" * 60)
    for name, info in BUILTIN_SEQUENCES.items():
        print(f"{name:<14} {info['length']:>8} bp  {info['description']}")


def get_sequence(name: str) -> str:
    """Return the nucleotide string for a built-in sequence name."""
    if name not in BUILTIN_SEQUENCES:
        names = ", ".join(BUILTIN_SEQUENCES)
        raise ValueError(f"Unknown sequence '{name}'. Available: {names}")
    return BUILTIN_SEQUENCES[name]["sequence"]
